
name: my tag action
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: frmalm/tag-action@main
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          prefix: my-prefix-v
          major: 11