
name: my tag action
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: frmalm/tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          prefix: my-prefix
          major: 11