
name: Bump version
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: frmalm/tag-action@main
        env:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          prefix: my-prefix